### ISSUE TITLE
CPU not listed on RPI4 Debian 12 bookworm

### ISSUE THREAD

**Issue by OzzyHelix** [Izder456/crfetch#2] opened 2024-06-28 00:46 UTC
the CPU is not listed on the raspberry pi with Debian 12 probably because /proc/cpuinfo doesn't have the info for the cpu that is in the rpi 4

![image](https://github.com/Izder456/crfetch/assets/29835364/19573822-070a-4dda-a773-0f81717963b2)

**Comment by Izder456** [comment] 2024-06-28 01:37
this is solved by using lscpu.

duplicate of #1, closing.

**Closed as completed** 2024-06-28 01:38 UTC
